export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const FETCH_LABELS = "FETCH_LABELS";
export const FETCH_GLOBALSETTING = "FETCH_LABELS";
export const FETCH_GLOBAL_SETTINGS = "FETCH_GLOBAL_SETTINGS";
